### ISSUE TITLE
Incompatibility of getVersion between lib/socket.js and example/conn.js

### ISSUE THREAD

**Issue by ar7bd** [ioBroker/ioBroker.socketio#38] opened 2020-11-20 11:24 UTC
**Describe the bug**  
In change 321b3ed1e09560e12c6904628391bafb2bc9d18c getVersion was modified to emit a 'null' as first argument (line 1200). Not sure if that is intended or not, but example/conn.js expects the version to be the first argument (line 403 and 417). either lib/socket.js should emit it as first argument or example/conn.js must be updated.

**To Reproduce**  
servConn.getStates never calls its callback routine, because _checkAuth always bails out due to version parameter being null.

**Expected behavior**  
Should work like before the change.

**Versions:**  
 - Adapter version: socket.io 3.0.13
 - JS-Controller version: 3.1.6
 - Node version: v10.22.1 
 - Operating system: ioBroker running on a Linux Nuc, conn.js used on Chrome/ Windows 10

**Comment by Apollon77** [comment] 2020-11-20 22:42
It was intended and yes example needs to be adjusted

**Comment by blumfisch** [comment] 2020-11-21 15:27
Im also using conn.js and have the same issue. Same versions as ar7bd. 

No reading of states at startup using conn.js and socket.io-adapter.

My solution:
I fiddled with line ~640 and commented the return:

` if (!this._checkConnection('getStates', arguments)) //return;`

Now it reads states at startup again but uses "slow pollung" instead of websockets (?)
Does NOT work, if you check "Only use Websockets" in socket.io-Adapter.

Would greatly appreciate an update so conn.js can run again as intended.

**Comment by Apollon77** [comment] 2020-11-28 22:59
in fact duplicate of #32 ... there is also a workaround posted https://github.com/ioBroker/ioBroker.socketio/issues/32#issuecomment-702320537

**Closed by Apollon77** 2020-11-28 22:59 UTC
